### ISSUE TITLE
how to use?

### ISSUE THREAD

**Issue by davoodkharmanzar** [josh4364/IL2cppStartProcess#3]
hello dear,
how to using this on unity?
thanks.

**Comment by zabszk** [comment]
Hi.

The C library needs to be compiled to .dll and it needs to be included in the unity project.

But we have found a way how to start a process without using any external library at all. I will post it on github in a couple of hours.

**Comment by zabszk** [comment]
Hi.

I have committed the changes to my fork of this repository zabszk/IL2cppStartProcess@19283f5f7012e7e2b230bb72c7eda9a35570ae5b and opened a Pull Request #4 .

It should be much easier to use, no library required.

**Comment by josh4364** [comment]
Let me know if you still need help.

**Comment by davoodkharmanzar** [comment]
> Let me know if you still need help.

hello and thanks for this :]

but how can i run an exe that exists on StreamingAssets folder?

StartExternalProcess.Start(Application.streamingAssetsPath, Application.streamingAssetsPath + "/EXEFILE" + args); ??
